Pairing lib on BN256 along with python tests.
sCrypt-Inc/boilerplate pull request #193
Opened 2022-07-12 16:11 UTC by msinkec

These tests take a long time to evaluate so we should also get #191 going before.

2022-07-12 23:04 UTC, xhliu requested changes
🥇 u r the champion! The largest and most sophisticated sCrypt contract! Really well done.


Some minor changes inline b4 merging.

Does `js` tests run at all? https://app.travis-ci.com/github/sCrypt-Inc/boilerplate/builds/253105388

Only 75% of tests in curve run?

> test_curve_bn256.py ...........................                          [ 75%]

2022-07-13 00:29 UTC, xhliu commented on tests/py/test_curve_bn256.py
> +            'y': -122496500026268596728444203481896352677017027832972886303288710168393500005538,
There should be no negative number in FQ. Missing `mod p`? Same everywhere.

2022-07-13 06:17 UTC, msinkec commented
> Does `js` tests run at all? https://app.travis-ci.com/github/sCrypt-Inc/boilerplate/builds/253105388
> 
> Only 75% of tests in curve run?
> 
> > test_curve_bn256.py ...........................                          [ 75%]

All Python tests ran. 75 % here means that test_curve_bn256.py  amounts for 75 % of all tests. The other ones are in test_pairing_bn256.py. However I'm not sure about js tests. Will check.

2022-07-13 06:23 UTC, msinkec commented on tests/py/res/testPairingBN256.scrypt
> +
We can but it will double the test time & resources used. Maybe just add a commented test? pair() itself is a very simple function after all.

2022-07-13 14:49 UTC, msinkec commented
Travis runs JS job now as well.

2022-07-14 15:56 UTC, xhliu commented on tests/py/res/testPairingBN256.scrypt
> +<!DOCTYPE html>
Why is this an html file?

2022-07-26 16:56 UTC, xhliu commented on contracts/zksnark.scrypt
> +        }
Replace CurvePoint w/ G1Point.

2022-07-27 04:53 UTC, msinkec commented
This should be done now. Travis seems to be running out of resources. Maybe we should disable zkSNARK tests and only run the pairing and curve tests?

2022-07-28 04:12 UTC, merged