Conversion
sCrypt-Inc/boilerplate pull request #233
Opened 2023-05-07 09:27 UTC by yusufidimaina9989

2023-05-08 02:34 UTC, xhliu requested changes
👍 awesome, code looks good.

Can you please do the following?

- move contracts to src/contracts
- add test for each contract under tests, both local and testnet.

2023-05-09 19:58 UTC, yusufidimaina9989 commented
open a new or

2023-06-22 17:43 UTC, xhliu approved these changes
👍

2023-06-22 17:43 UTC, xhliu commented on numbergs.testnet.ts
> +import { Numbergs } from '../../src/contracts/numbergs'
Move to test/ folder

2023-06-22 17:43 UTC, xhliu commented on BlockTimeBet.ts
> +import {assert, prop, method, SmartContract,Sha256, PubKey, Sig, FixedArray, checkSig} from 'scrypt-ts'
Put all these contracts under `sr/contracts/`

2023-06-22 17:43 UTC, xhliu commented on BlockTimeBet.ts
> +import {assert, prop, method, SmartContract,Sha256, PubKey, Sig, FixedArray, checkSig} from 'scrypt-ts'
Put all these contracts under `sr/contracts/`

2023-06-28 16:02 UTC, xhliu approved these changes
👍 well done

2023-06-28 16:02 UTC, merged