Add base58.ts and calle.ts
sCrypt-Inc/boilerplate pull request #252
Opened 2023-07-18 07:05 UTC by yusufidimaina9989

2023-07-18 17:05 UTC, Harunadangabas commented
Great work

2023-07-18 19:09 UTC, xhliu requested changes
👍 A few minor changes.

2023-07-18 19:09 UTC, xhliu commented on src/contracts/calle.ts
> +export class Calle extends SmartContract{
Calle -> Callee

2023-07-18 19:09 UTC, xhliu commented on src/contracts/calle.ts
> +
For each contract, let us add a link to the article, if any, as in https://github.com/sCrypt-Inc/boilerplate/blob/b649ab516abb5eda8c2e442c1a752252abe02446/src/contracts/accumulatorMultiSig.ts#L14

https://xiaohuiliu.medium.com/inter-contract-call-on-bitcoin-f51869c08be

2023-07-18 19:09 UTC, xhliu commented on src/contracts/cointossxor.ts
> +
https://xiaohuiliu.medium.com/fair-bitcoin-toss-7310256e60c3

2023-07-18 19:09 UTC, xhliu commented on src/contracts/lottery.ts
> +
https://xiaohuiliu.medium.com/secure-multiparty-computations-on-bitcoin-953a64843b94

2023-07-18 19:09 UTC, xhliu commented on src/contracts/cointossxor.ts
> +        const head : ByteString = (BigInt(aliceNonce) * BigInt(bobNonce)) && toByteString('0000000000000000000000000000000000000000000000000000000000000001')
`*` should be `xor` https://docs.scrypt.io/how-to-write-a-contract/built-ins#bitwise-operator

2023-07-20 02:14 UTC, zhfnjust commented on src/contracts/Callee.ts
> +    const data : ByteString = int2ByteString(co.a, Calle.N) + int2ByteString(co.b, Calle.N) + int2ByteString(co.c, Calle.N)
`Calle` -> `Callee`

2023-07-20 02:14 UTC, zhfnjust commented on src/contracts/Callee.ts
> +import { assert } from "console"
import `assert` from `scrypt-ts`

2023-07-20 02:15 UTC, zhfnjust commented on src/contracts/cointossxor.ts
> +import { assert } from "console";
import assert from scrypt-ts

2023-07-20 02:17 UTC, zhfnjust commented on src/contracts/lottery.ts
> +import { assert } from "console";
import assert from scrypt-ts

2023-07-20 09:01 UTC, yusufidimaina9989 commented on src/contracts/Callee.ts
> +import { assert } from "console"
ok sir

2023-07-24 17:10 UTC, merged