Use enum
sCrypt-Inc/boilerplate pull request #340
Opened 2024-04-03 08:23 UTC by yusufidimaina9989

2024-04-03 11:46 UTC, yusufidimaina9989 commented
https://github.com/sCrypt-Inc/boilerplate/issues/339

2024-07-19 07:50 UTC, msinkec requested changes
Don't use explicit values where not needed.

You can also apply an enum in `blindEscrow.ts`.

2024-07-19 07:50 UTC, msinkec commented on src/contracts/rockPaperScissors.ts
> +    ROCK = 0,
No explicit values needed to be defined here.

2024-07-19 13:38 UTC, msinkec approved these changes

2024-07-19 13:38 UTC, msinkec approved these changes

2024-07-19 13:38 UTC, merged