add sudoku.scrypt
sCrypt-Inc/boilerplate pull request #43
Opened 2021-01-04 02:09 UTC by zhfnjust

2021-01-04 03:45 UTC, xhliu requested changes
🥇

2021-01-04 03:45 UTC, xhliu commented on contracts/sudoku.scrypt
> +        // N - 2
remove

2021-01-04 03:45 UTC, xhliu commented on tests/js/sudoku.scrypttest.js
> +      hex = hex + (num2bin(arr[i][j]) === ''   ? '00' : num2bin(arr[i][j]));
hex = hex + (arr[i][j]) === 0   ? '00' : num2bin(arr[i][j]));

2021-01-04 03:45 UTC, xhliu commented on tests/js/sudoku.scrypttest.js
> +  it('should success', () => {
success -> succeed

2021-01-04 03:45 UTC, xhliu commented on tests/js/sudoku.scrypttest.js
> +  it('should failed', () => {
failed -> fail

2021-01-04 03:45 UTC, xhliu commented on tests/js/sudoku.scrypttest.js
> +  it('should failed', () => {
same

2021-01-04 03:45 UTC, xhliu commented on tests/js/sudoku.scrypttest.js
> +const validSolution2 = [
Unused. Delete.

2021-01-04 03:45 UTC, xhliu commented on tests/js/sudoku.scrypttest.js
> +const validSolution0 = [
Let's name this invalid, since it is NOT a valid solution.

2021-01-04 03:45 UTC, xhliu commented on tests/js/sudoku.scrypttest.js
> +const board = [
Let's have a "sparse" board, i.e., more `0`s, to be realistic.

2021-01-04 03:45 UTC, xhliu commented on contracts/sudoku.scrypt
> +        require(this.formatCheck(solution));
No need for a function here. Just check length.

2021-01-04 03:45 UTC, xhliu commented on contracts/sudoku.scrypt
> +    public function isValidSudoku(bytes solution) {
isValidSudoku -> solve

Pub function name should be a verb, like `unlock`.

2021-01-04 03:45 UTC, xhliu commented on contracts/sudoku.scrypt
> +                }
What's the solution format? Non-zero element in the initial board has to show up as well or not? If yes,
```
 else {
  // check `solution`'s non-empty element is the same with `this.board`, i.e., u cannot change the initial board.
}
```

If not, make sure they are 0.
```
else {
  // check 0
}
```

2021-01-04 03:45 UTC, xhliu commented on contracts/sudoku.scrypt
> +                int rowElem = Util.fromLEUnsigned(Util.getElemAt(newBord, this.index(i, j)));
Put this common code into a function

`Util.fromLEUnsigned(Util.getElemAt(newBord, this.index(i, j)))`

2021-01-04 03:45 UTC, xhliu commented on contracts/sudoku.scrypt
> +        bytes newBord = this.merge(solution);
merge -> formatCheck

2021-01-04 03:45 UTC, xhliu commented on contracts/sudoku.scrypt
> +            require(squareSum == 45);
Is this a sufficient condition to ensure a solution is found? Definitely a necessary condition. Can u have duplicate digits in this case, e.g., every element is set to 5, given initial board of only `0`s and `5`s. U need to check row, col, and subgrid has unique digits.

2021-01-04 04:53 UTC, xhliu commented on tests/js/sudoku.scrypttest.js
> +const board = [
E.g.
https://en.wikipedia.org/wiki/Sudoku#Variations_of_grid_sizes_or_region_shapes
https://rosettacode.org/wiki/Category:BBC_BASIC

2021-01-16 15:25 UTC, zhfnjust commented on contracts/sudoku.scrypt
> +        bytes newBord = this.merge(solution);
it not only format checking.

2021-01-16 17:10 UTC, xhliu approved these changes
awesome 💯

2021-01-16 17:10 UTC, xhliu commented on contracts/array.scrypt
> +contract Array {
👍 

I was planning to do this. We can wrap it into the standard library later for dynamic array.

2021-01-16 17:10 UTC, merged